[CmdletBinding()]
param(
    [string]$ArchiveName = 'Faster-Whisper-XXL_r245.4_FULL_MODERNIZED_RTX50_CUDA128_PY31021_2026-08-25.zip',
    [string]$GitSha = $env:GITHUB_SHA
)
$ErrorActionPreference='Stop'
Set-StrictMode -Version Latest
$workspace=(Get-Location).Path
$report=Join-Path $workspace 'extended-report'
if (-not (Test-Path (Join-Path $report 'candidate-success.json'))) { throw 'Candidate success marker missing.' }
$root=(Get-Content (Join-Path $report 'bundle-root.txt') -Raw).Trim()
if (-not (Test-Path $root -PathType Container)) { throw "Bundle root missing: $root" }
$contents=Join-Path $root '_xxl_data'

# Remove only caches generated by our source-stdlib imports/tests. Do not delete
# externalized original .pyc files; those contain the preserved custom XXL code.
Get-ChildItem $contents -Recurse -Directory -Filter __pycache__ -ErrorAction SilentlyContinue | Sort-Object FullName -Descending | Remove-Item -Recurse -Force -ErrorAction SilentlyContinue

& python tools\finalize_full_modernization.py $root $report --git-sha $GitSha *>&1 | Tee-Object -FilePath (Join-Path $report 'finalize-full.txt')
if ($LASTEXITCODE -ne 0) { throw "Final modernization metadata failed: $LASTEXITCODE" }

$files=Get-ChildItem $root -Recurse -File
$uncompressed=($files | Measure-Object Length -Sum).Sum
@{files=$files.Count;uncompressed_bytes=$uncompressed} | ConvertTo-Json | Set-Content (Join-Path $report 'final-bundle-footprint.json') -Encoding utf8

$zip=Join-Path $workspace $ArchiveName
Remove-Item $zip -Force -ErrorAction SilentlyContinue
$parent=Split-Path $root -Parent
Push-Location $parent
try {
    & 7z.exe a -tzip -mx=5 -mmt=on $zip '.\Faster-Whisper-XXL' *>&1 | Tee-Object -FilePath (Join-Path $report 'final-7z-create.txt')
    $rc=$LASTEXITCODE
} finally { Pop-Location }
if ($rc -ne 0) { throw "ZIP creation failed: $rc" }
& 7z.exe t $zip *>&1 | Tee-Object -FilePath (Join-Path $report 'final-7z-test.txt')
if ($LASTEXITCODE -ne 0) { throw "ZIP integrity test failed: $LASTEXITCODE" }
$zipItem=Get-Item $zip
$hash=(Get-FileHash $zip -Algorithm SHA256).Hash
$archiveInfo=[ordered]@{filename=$zipItem.Name;size_bytes=$zipItem.Length;sha256=$hash;files=$files.Count;uncompressed_bytes=$uncompressed}
$archiveInfo | ConvertTo-Json | Set-Content (Join-Path $report 'final-archive-info.json') -Encoding utf8

$hosting=[ordered]@{archive=$archiveInfo;gofile=$null;buzzheavier=$null;errors=@()}

try {
    $resp=Join-Path $report 'gofile-response.json'
    & curl.exe --location --fail-with-body --retry 4 --retry-all-errors --connect-timeout 30 --form "file=@$zip" --output $resp 'https://upload.gofile.io/uploadfile' 2>&1 | Tee-Object -FilePath (Join-Path $report 'gofile-curl.txt')
    if ($LASTEXITCODE -ne 0) { throw "Gofile upload curl exit $LASTEXITCODE" }
    $j=Get-Content $resp -Raw | ConvertFrom-Json
    if ($j.status -ne 'ok') { throw "Gofile status: $($j.status)" }
    $url=$j.data.downloadPage
    if (-not $url) { $url=$j.data.downloadPageUrl }
    if (-not $url) { throw 'Gofile response has no download page.' }
    & curl.exe --location --fail --retry 3 --retry-all-errors --max-time 120 --dump-header (Join-Path $report 'gofile-page-headers.txt') --output (Join-Path $report 'gofile-page.html') $url
    if ($LASTEXITCODE -ne 0) { throw "Gofile page GET failed: $LASTEXITCODE" }
    $hosting.gofile=[ordered]@{success=$true;url=$url;guestToken=$j.data.guestToken;parentFolder=$j.data.parentFolder}
    $url | Set-Content (Join-Path $report 'gofile-url.txt')
} catch {
    $hosting.errors += "Gofile: $($_.Exception.Message)"
    $hosting.gofile=[ordered]@{success=$false;error=$_.Exception.Message}
}

try {
    $resp=Join-Path $report 'buzzheavier-response.json'
    & curl.exe --location --fail-with-body --retry 4 --retry-all-errors --connect-timeout 30 --upload-file $zip --output $resp "https://w.buzzheavier.com/$ArchiveName" 2>&1 | Tee-Object -FilePath (Join-Path $report 'buzzheavier-curl.txt')
    if ($LASTEXITCODE -ne 0) { throw "Buzzheavier upload curl exit $LASTEXITCODE" }
    $j=Get-Content $resp -Raw | ConvertFrom-Json
    $id=$j.data.id
    if (-not $id) { throw 'Buzzheavier response has no data.id.' }
    $url="https://buzzheavier.com/$id"
    & curl.exe --location --fail --retry 3 --retry-all-errors --max-time 120 --dump-header (Join-Path $report 'buzzheavier-page-headers.txt') --output (Join-Path $report 'buzzheavier-page.html') $url
    if ($LASTEXITCODE -ne 0) { throw "Buzzheavier page GET failed: $LASTEXITCODE" }
    $hosting.buzzheavier=[ordered]@{success=$true;url=$url;id=$id}
    $url | Set-Content (Join-Path $report 'buzzheavier-url.txt')
} catch {
    $hosting.errors += "Buzzheavier: $($_.Exception.Message)"
    $hosting.buzzheavier=[ordered]@{success=$false;error=$_.Exception.Message}
}

$working=0
if ($hosting.gofile.success) { $working++ }
if ($hosting.buzzheavier.success) { $working++ }
$hosting.working_host_count=$working
$hosting | ConvertTo-Json -Depth 8 | Set-Content (Join-Path $report 'FINAL-DOWNLOAD-LINKS.json') -Encoding utf8
$hosting | ConvertTo-Json -Depth 8 | Write-Host
if ($working -eq 0) { throw 'No final hosting provider passed upload + download-page GET validation.' }

Write-Host "FINAL_ARCHIVE=$ArchiveName"
Write-Host "FINAL_SIZE=$($zipItem.Length)"
Write-Host "FINAL_SHA256=$hash"
if ($hosting.gofile.success) { Write-Host "FINAL_GOFILE=$($hosting.gofile.url)" }
if ($hosting.buzzheavier.success) { Write-Host "FINAL_BUZZHEAVIER=$($hosting.buzzheavier.url)" }
